import { Red_Hat_Text } from "next/font/google";
import "./globals.css";

const redHat = Red_Hat_Text({ subsets: ["latin"] });

export const metadata = {
  title: "Product List with Cart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={redHat.className}>{children}</body>
    </html>
  );
}
